/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
        "redirectUrl": string;
    }
    interface AppRoot {
    }
    interface OnlingoAdmin {
    }
    interface OnlingoAdminAttachments {
    }
    interface OnlingoAdminClassrooms {
    }
    interface OnlingoAdminDashboard {
    }
    interface OnlingoAdminFacilitators {
    }
    interface OnlingoAdminPosts {
    }
    interface OnlingoAdminStudents {
    }
    interface OnlingoAdminUsers {
    }
    interface OnlingoChangePassword {
        "redirectUrl": string;
    }
    interface OnlingoClassroom {
        "classroomCode": string;
    }
    interface OnlingoClassroomVideo {
        "classroomCode": string;
        "videoSessionCode": string;
    }
    interface OnlingoFacilitator {
    }
    interface OnlingoRegister {
        "redirectUrl": string;
    }
    interface OnlingoResetPassword {
    }
    interface OnlingoStudent {
    }
    interface OnlingoUser {
    }
    interface OnlingoUserDashboard {
    }
    interface OnlingoUserGrades {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLOnlingoAdminElement extends Components.OnlingoAdmin, HTMLStencilElement {
    }
    var HTMLOnlingoAdminElement: {
        prototype: HTMLOnlingoAdminElement;
        new (): HTMLOnlingoAdminElement;
    };
    interface HTMLOnlingoAdminAttachmentsElement extends Components.OnlingoAdminAttachments, HTMLStencilElement {
    }
    var HTMLOnlingoAdminAttachmentsElement: {
        prototype: HTMLOnlingoAdminAttachmentsElement;
        new (): HTMLOnlingoAdminAttachmentsElement;
    };
    interface HTMLOnlingoAdminClassroomsElement extends Components.OnlingoAdminClassrooms, HTMLStencilElement {
    }
    var HTMLOnlingoAdminClassroomsElement: {
        prototype: HTMLOnlingoAdminClassroomsElement;
        new (): HTMLOnlingoAdminClassroomsElement;
    };
    interface HTMLOnlingoAdminDashboardElement extends Components.OnlingoAdminDashboard, HTMLStencilElement {
    }
    var HTMLOnlingoAdminDashboardElement: {
        prototype: HTMLOnlingoAdminDashboardElement;
        new (): HTMLOnlingoAdminDashboardElement;
    };
    interface HTMLOnlingoAdminFacilitatorsElement extends Components.OnlingoAdminFacilitators, HTMLStencilElement {
    }
    var HTMLOnlingoAdminFacilitatorsElement: {
        prototype: HTMLOnlingoAdminFacilitatorsElement;
        new (): HTMLOnlingoAdminFacilitatorsElement;
    };
    interface HTMLOnlingoAdminPostsElement extends Components.OnlingoAdminPosts, HTMLStencilElement {
    }
    var HTMLOnlingoAdminPostsElement: {
        prototype: HTMLOnlingoAdminPostsElement;
        new (): HTMLOnlingoAdminPostsElement;
    };
    interface HTMLOnlingoAdminStudentsElement extends Components.OnlingoAdminStudents, HTMLStencilElement {
    }
    var HTMLOnlingoAdminStudentsElement: {
        prototype: HTMLOnlingoAdminStudentsElement;
        new (): HTMLOnlingoAdminStudentsElement;
    };
    interface HTMLOnlingoAdminUsersElement extends Components.OnlingoAdminUsers, HTMLStencilElement {
    }
    var HTMLOnlingoAdminUsersElement: {
        prototype: HTMLOnlingoAdminUsersElement;
        new (): HTMLOnlingoAdminUsersElement;
    };
    interface HTMLOnlingoChangePasswordElement extends Components.OnlingoChangePassword, HTMLStencilElement {
    }
    var HTMLOnlingoChangePasswordElement: {
        prototype: HTMLOnlingoChangePasswordElement;
        new (): HTMLOnlingoChangePasswordElement;
    };
    interface HTMLOnlingoClassroomElement extends Components.OnlingoClassroom, HTMLStencilElement {
    }
    var HTMLOnlingoClassroomElement: {
        prototype: HTMLOnlingoClassroomElement;
        new (): HTMLOnlingoClassroomElement;
    };
    interface HTMLOnlingoClassroomVideoElement extends Components.OnlingoClassroomVideo, HTMLStencilElement {
    }
    var HTMLOnlingoClassroomVideoElement: {
        prototype: HTMLOnlingoClassroomVideoElement;
        new (): HTMLOnlingoClassroomVideoElement;
    };
    interface HTMLOnlingoFacilitatorElement extends Components.OnlingoFacilitator, HTMLStencilElement {
    }
    var HTMLOnlingoFacilitatorElement: {
        prototype: HTMLOnlingoFacilitatorElement;
        new (): HTMLOnlingoFacilitatorElement;
    };
    interface HTMLOnlingoRegisterElement extends Components.OnlingoRegister, HTMLStencilElement {
    }
    var HTMLOnlingoRegisterElement: {
        prototype: HTMLOnlingoRegisterElement;
        new (): HTMLOnlingoRegisterElement;
    };
    interface HTMLOnlingoResetPasswordElement extends Components.OnlingoResetPassword, HTMLStencilElement {
    }
    var HTMLOnlingoResetPasswordElement: {
        prototype: HTMLOnlingoResetPasswordElement;
        new (): HTMLOnlingoResetPasswordElement;
    };
    interface HTMLOnlingoStudentElement extends Components.OnlingoStudent, HTMLStencilElement {
    }
    var HTMLOnlingoStudentElement: {
        prototype: HTMLOnlingoStudentElement;
        new (): HTMLOnlingoStudentElement;
    };
    interface HTMLOnlingoUserElement extends Components.OnlingoUser, HTMLStencilElement {
    }
    var HTMLOnlingoUserElement: {
        prototype: HTMLOnlingoUserElement;
        new (): HTMLOnlingoUserElement;
    };
    interface HTMLOnlingoUserDashboardElement extends Components.OnlingoUserDashboard, HTMLStencilElement {
    }
    var HTMLOnlingoUserDashboardElement: {
        prototype: HTMLOnlingoUserDashboardElement;
        new (): HTMLOnlingoUserDashboardElement;
    };
    interface HTMLOnlingoUserGradesElement extends Components.OnlingoUserGrades, HTMLStencilElement {
    }
    var HTMLOnlingoUserGradesElement: {
        prototype: HTMLOnlingoUserGradesElement;
        new (): HTMLOnlingoUserGradesElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "onlingo-admin": HTMLOnlingoAdminElement;
        "onlingo-admin-attachments": HTMLOnlingoAdminAttachmentsElement;
        "onlingo-admin-classrooms": HTMLOnlingoAdminClassroomsElement;
        "onlingo-admin-dashboard": HTMLOnlingoAdminDashboardElement;
        "onlingo-admin-facilitators": HTMLOnlingoAdminFacilitatorsElement;
        "onlingo-admin-posts": HTMLOnlingoAdminPostsElement;
        "onlingo-admin-students": HTMLOnlingoAdminStudentsElement;
        "onlingo-admin-users": HTMLOnlingoAdminUsersElement;
        "onlingo-change-password": HTMLOnlingoChangePasswordElement;
        "onlingo-classroom": HTMLOnlingoClassroomElement;
        "onlingo-classroom-video": HTMLOnlingoClassroomVideoElement;
        "onlingo-facilitator": HTMLOnlingoFacilitatorElement;
        "onlingo-register": HTMLOnlingoRegisterElement;
        "onlingo-reset-password": HTMLOnlingoResetPasswordElement;
        "onlingo-student": HTMLOnlingoStudentElement;
        "onlingo-user": HTMLOnlingoUserElement;
        "onlingo-user-dashboard": HTMLOnlingoUserDashboardElement;
        "onlingo-user-grades": HTMLOnlingoUserGradesElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
        "redirectUrl"?: string;
    }
    interface AppRoot {
    }
    interface OnlingoAdmin {
    }
    interface OnlingoAdminAttachments {
    }
    interface OnlingoAdminClassrooms {
    }
    interface OnlingoAdminDashboard {
    }
    interface OnlingoAdminFacilitators {
    }
    interface OnlingoAdminPosts {
    }
    interface OnlingoAdminStudents {
    }
    interface OnlingoAdminUsers {
    }
    interface OnlingoChangePassword {
        "redirectUrl"?: string;
    }
    interface OnlingoClassroom {
        "classroomCode"?: string;
    }
    interface OnlingoClassroomVideo {
        "classroomCode"?: string;
        "videoSessionCode"?: string;
    }
    interface OnlingoFacilitator {
    }
    interface OnlingoRegister {
        "redirectUrl"?: string;
    }
    interface OnlingoResetPassword {
    }
    interface OnlingoStudent {
    }
    interface OnlingoUser {
    }
    interface OnlingoUserDashboard {
    }
    interface OnlingoUserGrades {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-root": AppRoot;
        "onlingo-admin": OnlingoAdmin;
        "onlingo-admin-attachments": OnlingoAdminAttachments;
        "onlingo-admin-classrooms": OnlingoAdminClassrooms;
        "onlingo-admin-dashboard": OnlingoAdminDashboard;
        "onlingo-admin-facilitators": OnlingoAdminFacilitators;
        "onlingo-admin-posts": OnlingoAdminPosts;
        "onlingo-admin-students": OnlingoAdminStudents;
        "onlingo-admin-users": OnlingoAdminUsers;
        "onlingo-change-password": OnlingoChangePassword;
        "onlingo-classroom": OnlingoClassroom;
        "onlingo-classroom-video": OnlingoClassroomVideo;
        "onlingo-facilitator": OnlingoFacilitator;
        "onlingo-register": OnlingoRegister;
        "onlingo-reset-password": OnlingoResetPassword;
        "onlingo-student": OnlingoStudent;
        "onlingo-user": OnlingoUser;
        "onlingo-user-dashboard": OnlingoUserDashboard;
        "onlingo-user-grades": OnlingoUserGrades;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "onlingo-admin": LocalJSX.OnlingoAdmin & JSXBase.HTMLAttributes<HTMLOnlingoAdminElement>;
            "onlingo-admin-attachments": LocalJSX.OnlingoAdminAttachments & JSXBase.HTMLAttributes<HTMLOnlingoAdminAttachmentsElement>;
            "onlingo-admin-classrooms": LocalJSX.OnlingoAdminClassrooms & JSXBase.HTMLAttributes<HTMLOnlingoAdminClassroomsElement>;
            "onlingo-admin-dashboard": LocalJSX.OnlingoAdminDashboard & JSXBase.HTMLAttributes<HTMLOnlingoAdminDashboardElement>;
            "onlingo-admin-facilitators": LocalJSX.OnlingoAdminFacilitators & JSXBase.HTMLAttributes<HTMLOnlingoAdminFacilitatorsElement>;
            "onlingo-admin-posts": LocalJSX.OnlingoAdminPosts & JSXBase.HTMLAttributes<HTMLOnlingoAdminPostsElement>;
            "onlingo-admin-students": LocalJSX.OnlingoAdminStudents & JSXBase.HTMLAttributes<HTMLOnlingoAdminStudentsElement>;
            "onlingo-admin-users": LocalJSX.OnlingoAdminUsers & JSXBase.HTMLAttributes<HTMLOnlingoAdminUsersElement>;
            "onlingo-change-password": LocalJSX.OnlingoChangePassword & JSXBase.HTMLAttributes<HTMLOnlingoChangePasswordElement>;
            "onlingo-classroom": LocalJSX.OnlingoClassroom & JSXBase.HTMLAttributes<HTMLOnlingoClassroomElement>;
            "onlingo-classroom-video": LocalJSX.OnlingoClassroomVideo & JSXBase.HTMLAttributes<HTMLOnlingoClassroomVideoElement>;
            "onlingo-facilitator": LocalJSX.OnlingoFacilitator & JSXBase.HTMLAttributes<HTMLOnlingoFacilitatorElement>;
            "onlingo-register": LocalJSX.OnlingoRegister & JSXBase.HTMLAttributes<HTMLOnlingoRegisterElement>;
            "onlingo-reset-password": LocalJSX.OnlingoResetPassword & JSXBase.HTMLAttributes<HTMLOnlingoResetPasswordElement>;
            "onlingo-student": LocalJSX.OnlingoStudent & JSXBase.HTMLAttributes<HTMLOnlingoStudentElement>;
            "onlingo-user": LocalJSX.OnlingoUser & JSXBase.HTMLAttributes<HTMLOnlingoUserElement>;
            "onlingo-user-dashboard": LocalJSX.OnlingoUserDashboard & JSXBase.HTMLAttributes<HTMLOnlingoUserDashboardElement>;
            "onlingo-user-grades": LocalJSX.OnlingoUserGrades & JSXBase.HTMLAttributes<HTMLOnlingoUserGradesElement>;
        }
    }
}
